version: '3.1'

services:

  wordpress:
    container_name: 'wordpress-main'
    depends_on:
      - db
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DEBUG: 'true'
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_LOG', true );
        define( 'SCRIPT_DEBUG', true );
        define( 'WP_DEVELOPMENT_MODE', true );
    volumes:
      - "./vendor/wordpress:/var/www/html"
      - "./src/plugins:/var/www/html/wp-content/plugins"
      - "./src/themes:/var/www/html/wp-content/themes"
      - "./custom.ini:/usr/local/etc/php/conf.d/custom.ini"

  db:
    container_name: 'wordpress-db'
    image: mariadb:10.6.4-focal
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    container_name: 'wordpress-phpmyadmin'
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: examplepass
      UPLOAD_LIMIT: 2G
    depends_on:
      - db

volumes:
  wordpress:
  db: