services:

  wordpress:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - ${WORDPRESS_PORT}:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_DEBUG: 'true'
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_LOG', true );
        define( 'SCRIPT_DEBUG', true );
        define( 'WP_DEVELOPMENT_MODE', true );
    volumes:
      - "./vendor/wordpress:/var/www/html"
      - "./src/plugins:/var/www/html/wp-content/plugins"
      - "./src/themes:/var/www/html/wp-content/themes"
      - "./custom.ini:/usr/local/etc/php/conf.d/custom.ini"

  db:
    image: mariadb:10.6.4-focal
    restart: on-failure
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: on-failure
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      UPLOAD_LIMIT: 2G
    depends_on:
      - db

volumes:
  wordpress:
  db: